/* Generated by Astilba Env. Do not edit. */
import {
  checkProcessTarget,
  loadProcessTarget,
  type ProcessSource,
  type ProcessTargetDefinition,
} from "@astilba/env/runtime";

export interface Configuration {
  readonly "siteOrigin"?: string;
}

const definition = (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "bindings", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "siteOrigin" });
  Object.defineProperty(output, "source", { enumerable: true, value: "ASTILBA_SITE" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "generated", { enumerable: true, value: "astilba.env.generated-module/v1" });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "build" });
  Object.defineProperty(output, "projection", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "canonicalisation", { enumerable: true, value: "astilba.jcs/v1" });
  Object.defineProperty(output, "codecAbi", { enumerable: true, value: "astilba.env.codec/v1" });
  Object.defineProperty(output, "consumer", { enumerable: true, value: "site" });
  Object.defineProperty(output, "contract", { enumerable: true, value: "com.astilba.web" });
  Object.defineProperty(output, "entries", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.origin-ascii/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "origin" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.web","siteOrigin"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "build" });
  Object.defineProperty(output, "name", { enumerable: true, value: "siteOrigin" });
  Object.defineProperty(output, "required", { enumerable: true, value: false });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "format", { enumerable: true, value: "astilba.env.projection" });
  Object.defineProperty(output, "formatVersion", { enumerable: true, value: 1 });
  Object.defineProperty(output, "kind", { enumerable: true, value: "server" });
  Object.defineProperty(output, "projectionAbi", { enumerable: true, value: "astilba.env.projection/v1" });
  return Object.freeze(output);
})() });
  return Object.freeze(output);
})() as ProcessTargetDefinition;

export const check = (source: ProcessSource) =>
  checkProcessTarget<Configuration>(definition, source);

export const load = (source: ProcessSource): Configuration =>
  loadProcessTarget<Configuration>(definition, source);
