export const createProjectManifestSchemaV1 = {
  $id: "https://astilba.com/schemas/create/v1.json",
  $schema: "https://json-schema.org/draft/2020-12/schema",
  additionalProperties: false,
  description:
    "The ownership and version manifest generated by create-astilba.",
  properties: {
    $schema: {
      const: "https://astilba.com/schemas/create/v1.json",
      type: "string",
    },
    features: {
      description: "Reserved feature identifiers. Version 1 requires none.",
      items: false,
      maxItems: 0,
      type: "array",
    },
    generator: {
      additionalProperties: false,
      properties: {
        name: {
          const: "create-astilba",
          type: "string",
        },
        version: {
          minLength: 1,
          type: "string",
        },
      },
      required: ["name", "version"],
      type: "object",
    },
    ownership: {
      additionalProperties: false,
      properties: {
        managed: {
          items: { $ref: "#/$defs/ownedDigest" },
          type: "array",
        },
        metadata: {
          const: ".astilba/project.json",
          type: "string",
        },
        seeded: {
          items: { $ref: "#/$defs/projectPath" },
          type: "array",
        },
        structured: {
          items: { $ref: "#/$defs/structuredFile" },
          type: "array",
        },
        symlinks: {
          items: { $ref: "#/$defs/symlink" },
          type: "array",
        },
      },
      required: ["managed", "metadata", "seeded", "structured", "symlinks"],
      type: "object",
    },
    recipe: {
      additionalProperties: false,
      properties: {
        id: {
          enum: [
            "typescript-library",
            "react-vite-spa",
            "astro-static-site",
            "cloudflare-worker-service",
          ],
          type: "string",
        },
        version: {
          minimum: 1,
          type: "integer",
        },
      },
      required: ["id", "version"],
      type: "object",
    },
    schemaVersion: {
      const: 1,
      type: "integer",
    },
  },
  required: [
    "$schema",
    "features",
    "generator",
    "ownership",
    "recipe",
    "schemaVersion",
  ],
  title: "Astilba Create project manifest v1",
  type: "object",
  $defs: {
    digest: {
      pattern: "^[0-9a-f]{64}$",
      type: "string",
    },
    ownedDigest: {
      additionalProperties: false,
      properties: {
        path: { $ref: "#/$defs/projectPath" },
        sha256: { $ref: "#/$defs/digest" },
      },
      required: ["path", "sha256"],
      type: "object",
    },
    projectPath: {
      description:
        "A normalized, portable path relative to the generated project root.",
      pattern:
        '^(?!/)(?![A-Za-z]:)(?!.*\\\\)(?!.*//)(?!.*\\/$)(?!.*[<>:"|?*])(?!.*(?:^|/)(?:\\.|\\.\\.|\\.[gG][iI][tT]|\\.[aA][sS][tT][iI][lL][bB][aA]-[cC][rR][eE][aA][tT][eE]-[iI][nN][cC][oO][mM][pP][lL][eE][tT][eE])(?:/|$))(?!.*(?:^|/)(?:[aA][uU][xX]|[cC][oO][nN]|[nN][uU][lL]|[pP][rR][nN]|[cC][oO][mM][1-9]|[lL][pP][tT][1-9])(?:\\.|/|$))(?!.*[. ](?:/|$))[\\x20-\\x7E]+$',
      type: "string",
    },
    structuredField: {
      additionalProperties: false,
      properties: {
        pointer: {
          pattern: "^(?:/(?:[^~/]|~[01])*)+$",
          type: "string",
        },
        sha256: { $ref: "#/$defs/digest" },
      },
      required: ["pointer", "sha256"],
      type: "object",
    },
    structuredFile: {
      additionalProperties: false,
      properties: {
        fields: {
          items: { $ref: "#/$defs/structuredField" },
          type: "array",
        },
        path: { $ref: "#/$defs/projectPath" },
      },
      required: ["fields", "path"],
      type: "object",
    },
    symlink: {
      additionalProperties: false,
      properties: {
        path: { $ref: "#/$defs/projectPath" },
        target: { $ref: "#/$defs/projectPath" },
      },
      required: ["path", "target"],
      type: "object",
    },
  },
} as const;
